name: Build and Release (Windows AMD64)

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

env:
  PLATFORM: windows-amd64

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "25"
          java-package: jdk+jmods # jmods is required by jlink

      - name: Checkout Xplora-Core Repository
        uses: actions/checkout@v7
        with:
          repository: Unofficial-Integrations/Xplora-Core
          token: ${{ secrets.XPLORA_BUILD_TOKEN }}
          path: xplora-core

      - name: Install Xplora-Core Artifact
        working-directory: xplora-core
        run: mvn -B install -DskipTests

      - name: Checkout Xplora-Swing-Extensions Repository
        uses: actions/checkout@v7
        with:
          repository: Unofficial-Integrations/Xplora-Swing-Extensions
          token: ${{ secrets.XPLORA_BUILD_TOKEN }}
          path: xplora-swing-extensions

      - name: Install Xplora-Swing-Extensions Artifact
        working-directory: xplora-swing-extensions
        run: mvn -B install -DskipTests

      - name: Checkout Xplora-Desktop-App Repository
        uses: actions/checkout@v7
        with:
          repository: Unofficial-Integrations/Xplora-Desktop-Swing
          token: ${{ secrets.XPLORA_BUILD_TOKEN }}
          path: xplora-swing

      - name: Build Xplora-Desktop-App
        working-directory: xplora-swing
        run: mvn -B -Pdist package jpackage:jpackage@win

      - name: Pack Xplora-Desktop-App
        shell: pwsh
        working-directory: xplora-swing
        run: |
          Compress-Archive `
            -Path target\release\Xplora\* `
            -DestinationPath Xplora-${{ github.ref_name }}-${{ env.PLATFORM }}.zip

      - name: Upload Xplora-Desktop-App
        uses: actions/upload-artifact@v7
        with:
          name: Xplora--${{ env.PLATFORM }}
          path: xplora-swing/Xplora-${{ github.ref_name }}-${{ env.PLATFORM }}.zip
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Xplora-Desktop-App
        uses: actions/download-artifact@v8
        with:
          name: Xplora-${{ env.PLATFORM }}
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: artifacts/Xplora-${{ github.ref_name }}-${{ env.PLATFORM }}.zip
